server:
  port: 9002

spring:
  application:
    name: STUDENT-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka/

  instance:
    hostname: localhost